### ISSUE TITLE
weights2gdf not working

### ISSUE THREAD

**Issue by fxpopp** [okunator/cellseg_gsontools#25]
I have segmented a WSI and extracted a 512x512 patch from it by `hap_cells = cells.cx[x:x+512, y:y+512]`.

![image](https://github.com/okunator/cellseg_gsontools/assets/38974891/bc52e37c-101b-41bd-ac0c-d5155da68552)

![image](https://github.com/okunator/cellseg_gsontools/assets/38974891/823b49f9-1211-447a-9357-a846b1db4328)

Following the user guide "[Cell/Nuclei Neighborhood Distances and Characteristics](https://okunator.github.io/cellseg_gsontools/user_guide/cell_neighborhood_characteristics/)", I would like to fit a connectivity graph to the resulting 157 cells. When executing `w = fit_graph(hap_cells, type="delaunay", thresh=200, id_col="uid")` I get many warnings like this:

1. passing a BlockManager to GeoDataFrame is deprecated and will be removed in a future version. Use public APIs instead.
2. the geometry is in a geographic CRS. The results of 'centroid' are probably wrong. Use 'GeoSeries.to_crs()' to reproject geometries to a projected CRS before this operation.
![image](https://github.com/okunator/cellseg_gsontools/assets/38974891/6d22f1a4-35cd-432f-9c3e-7cd10fa1884c)

When running `wdf = weights2gdf(hap_cells, w)` I get an error:

TypeError: sequence item 0: expected str instance, NoneType found

![image](https://github.com/okunator/cellseg_gsontools/assets/38974891/fc500c15-4737-499f-a0d6-3440e199d22a)

What could be the reason for this and what have I done wrong? Can you help me?

**Comment by okunator** [comment]
Hi, seems like your cell type column is called 'classification'. If you rename that column to 'class_name', then I believe your code would start working. All the methods in this library expect that the cell type class info is under the 'class_name' column.

**Comment by okunator** [comment]
Also, the warnings you get are nothing major. The second warning especially can be avoided by setting the crs of the gdf for example `hap_cells.set_crs(4328, inplace=True, allow_override=True)`
